# permissions for end users to view prometheusquerymappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheusquerymapping-viewer-role
rules:
- apiGroups:
  - metrics.turbonomic.io
  resources:
  - prometheusquerymappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.turbonomic.io
  resources:
  - prometheusquerymappings/status
  verbs:
  - get
