# permissions for end users to edit prometheusserverconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheusserverconfig-editor-role
rules:
- apiGroups:
  - metrics.turbonomic.io
  resources:
  - prometheusserverconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metrics.turbonomic.io
  resources:
  - prometheusserverconfigs/status
  verbs:
  - get
