# permissions for end users to view prometheusserverconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheusserverconfig-viewer-role
rules:
- apiGroups:
  - metrics.turbonomic.io
  resources:
  - prometheusserverconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.turbonomic.io
  resources:
  - prometheusserverconfigs/status
  verbs:
  - get
