---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - metrics.turbonomic.io
  resources:
  - prometheusquerymappings
  - prometheusserverconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metrics.turbonomic.io
  resources:
  - prometheusquerymappings/finalizers
  - prometheusserverconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - metrics.turbonomic.io
  resources:
  - prometheusquerymappings/status
  - prometheusserverconfigs/status
  verbs:
  - get
  - patch
  - update
